ROI:
  - [0, 500]     # верхний левый угол трапеции
  - [2688, 500]    # верхний правый угол трапеции
  - [2688, 1512]    # нижний правый угол (нижний правый край кадра)
  - [0, 1512]       # нижний левый угол (нижний левый край кадра)

WHITE_LIST: {
    2: "car",        # ID для автомобиля
    3: "motorcycle", # ID для мотоцикла
    7: "truck",      # ID для грузовика
    5: "bus",        # ID для автобуса
}