roi_polygon:
  - [0, 500]     # верхний левый угол трапеции
  - [2688, 500]    # верхний правый угол трапеции
  - [2688, 1512]    # нижний правый угол (нижний правый край кадра)
  - [0, 1512]       # нижний левый угол (нижний левый край кадра)

